import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";

type Props = {
  orderNumber: string;
  customerName: string;
  customerEmail: string;
  itemCount: number;
  total: string;
  paymentStatus: string;
  orderUrl: string;
};

export default function NewOrderAdminEmail({
  orderNumber,
  customerName,
  customerEmail,
  itemCount,
  total,
  paymentStatus,
  orderUrl,
}: Props) {
  return (
    <Html>
      <Head />

      <Preview>New order received - {orderNumber}</Preview>

      <Body
        style={{
          backgroundColor: "#f6f9fc",
          fontFamily: "Arial, sans-serif",
          padding: "20px",
        }}
      >
        <Container
          style={{
            backgroundColor: "#ffffff",
            padding: "32px",
            borderRadius: "8px",
          }}
        >
          <Heading>🛍️ New Order Received</Heading>

          <Text>
            A customer has successfully placed a new order.
          </Text>

          <Section>
            <Text><strong>Order Number:</strong> {orderNumber}</Text>
            <Text><strong>Customer:</strong> {customerName}</Text>
            <Text><strong>Email:</strong> {customerEmail}</Text>
            <Text><strong>Items:</strong> {itemCount}</Text>
            <Text><strong>Total:</strong> {total}</Text>
            <Text><strong>Payment Status:</strong> {paymentStatus}</Text>
          </Section>

          <Button
            href={orderUrl}
            style={{
              backgroundColor: "#000",
              color: "#fff",
              padding: "12px 20px",
              borderRadius: "6px",
              textDecoration: "none",
              display: "inline-block",
            }}
          >
            View Order
          </Button>

          <Text style={{ marginTop: 32, fontSize: 14, color: "#666" }}>
            This email was automatically generated by the Meka.WC store.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}